// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xVwW7bMAz9FYPb0ai9dbv4trXDUAzBhh12KYJBlRlbrS2pEhMgCPzvg2Q7ViwvaIBi",
	"h90Sk3p8fHyiDsBVq5VESRaKA2hmWIuExv/jNWsalBX+blWJ7kuJlhuhSSgJxRRPaK8RUhDu6/MWzR5S",
	"kKzFMKkHScHyGlvm0PypAiwZISvoui4Fg1YradHX/2KMMp6IkoSS3E+mdSM4cwyyR+toHALEtwY3UMCb",
	"bGor66M282g/B/y+2mk7PiExU8bI1ZO5YZp47atoozQaEj3LUZtztW9GEVYuuUtBKslxQYMUrKgko61Z",
	"jpJo0RJr9XLU7IPv6uEROUEv6/NWGCyhuIdhDNQPyfMIcUMGaxegxoGN7adz9BSOzcXalIzYi7W5dcnn",
	"tWENBQEhCSs0UYe+6tSbPxW2cuR7rpnbgXp06rZH//vJ1WCI6ORqUH7e1qkzIxH5iDc/N6obUWnRWlYt",
	"HZopxXtGY34g0imnqF0HJORGjbeTcTeY6EoNrkk+/biDCZsfvbRDY/vMd1e5Y640SqYFFHB9lV/lkIJm",
	"VHsZMj7dwAopXkcVUsKSISvhwZSdmn5l3JVQwFeU7i9Olg7X3v2yW6eUbLbRuvVsbb3P84uW1oXTnqWH",
	"l+9F1yw2wTGyTl/PSwPh9aJ1Tgf3/Zsr9KGXbamHo7z9EnfZHy/IdhW1sguW2aERm30yGfLUKb98ePKJ",
	"axctfVbl/tWepRG9i9+/f2ok9RQkPyjVIJPRjNXT/+sR/96j2Y1bYGsaKKAm0kWWNYqzplaWius8z6Fb",
	"d38CAAD//yutPaY7CQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
