// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package apiv1

// Captcha defines model for Captcha.
type Captcha struct {
	Mode      ChallengeMode          `json:"mode"`
	Nonce     string                 `json:"nonce"`
	Signature string                 `json:"signature"`
	Timestamp string                 `json:"timestamp"`
	Try       map[string]interface{} `json:"try"`
}

// Challenge defines model for Challenge.
type Challenge struct {
	Data  ChallengeData `json:"data"`
	Nonce string        `json:"nonce"`
	Salt  int           `json:"salt"`
}

// ChallengeData defines model for ChallengeData.
type ChallengeData map[string]interface{}

// ChallengeMode defines model for ChallengeMode.
type ChallengeMode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string                  `json:"code"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
}

// Error defines model for Error.
type Error ErrorResponse

// GenerateCaptchaParams defines parameters for GenerateCaptcha.
type GenerateCaptchaParams struct {
	// challenge type
	ChallengeMode *ChallengeMode `json:"challenge_mode,omitempty"`
}

// VerifyCaptchaJSONBody defines parameters for VerifyCaptcha.
type VerifyCaptchaJSONBody Captcha

// VerifyCaptchaJSONRequestBody defines body for VerifyCaptcha for application/json ContentType.
type VerifyCaptchaJSONRequestBody VerifyCaptchaJSONBody
