// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package apiv1

// token generated after credential check
type AuthenticatedToken string

// CredentialConfig defines model for CredentialConfig.
type CredentialConfig map[string]interface{}

// CredentialIdentifiers defines model for CredentialIdentifiers.
type CredentialIdentifiers struct {
	Credential  CredentialObject   `json:"credential"`
	Identifiers []IdentifierObject `json:"identifiers"`
}

// CredentialObject defines model for CredentialObject.
type CredentialObject struct {
	Config     *CredentialConfig `json:"config,omitempty"`
	Id         *string           `json:"id,omitempty"`
	IdentityId *IdentityId       `json:"identity_id,omitempty"`
	Type       CredentialType    `json:"type"`
}

// CredentialType defines model for CredentialType.
type CredentialType string

// DomainId defines model for DomainId.
type DomainId string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string                  `json:"code"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
}

// Identifier defines model for Identifier.
type Identifier string

// IdentifierCredentials defines model for IdentifierCredentials.
type IdentifierCredentials struct {
	Credentials *[]CredentialObject `json:"credentials,omitempty"`
	Identifier  *IdentifierObject   `json:"identifier,omitempty"`
}

// IdentifierId defines model for IdentifierId.
type IdentifierId string

// IdentifierObject defines model for IdentifierObject.
type IdentifierObject struct {
	DomainId   DomainId      `json:"domain_id"`
	Id         *IdentifierId `json:"id,omitempty"`
	Identifier Identifier    `json:"identifier"`

	// accno:account number, idcard:id card, mobile:mobile phone, email:email address
	IdentifierType IdentifierType `json:"identifier_type"`

	// token use in identifer's verification
	IdentifierVerifiyToken *IdentifierVerifyToken `json:"identifier_verifiy_token,omitempty"`
	IdentityId             *IdentityId            `json:"identity_id,omitempty"`
}

// accno:account number, idcard:id card, mobile:mobile phone, email:email address
type IdentifierType string

// token use in identifer's verification
type IdentifierVerifyToken string

// Identity defines model for Identity.
type Identity struct {
	Credentials *[]CredentialIdentifiers `json:"credentials,omitempty"`
	DomainId    *DomainId                `json:"domain_id,omitempty"`
	Id          *IdentityId              `json:"id,omitempty"`
	State       *State                   `json:"state,omitempty"`
}

// IdentityId defines model for IdentityId.
type IdentityId string

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// State defines model for State.
type State string

// Error defines model for Error.
type Error ErrorResponse

// Ok defines model for Ok.
type Ok OkResponse

// CheckCredentialForAuthenticationJSONBody defines parameters for CheckCredentialForAuthentication.
type CheckCredentialForAuthenticationJSONBody struct {
	CredentialConfig CredentialConfig `json:"credential_config"`
	CredentialType   CredentialType   `json:"credential_type"`
	DomainId         DomainId         `json:"domain_id"`
	Identifier       Identifier       `json:"identifier"`

	// accno:account number, idcard:id card, mobile:mobile phone, email:email address
	IdentifierType IdentifierType `json:"identifier_type"`
}

// GenerateCredentialForAuthenticationJSONBody defines parameters for GenerateCredentialForAuthentication.
type GenerateCredentialForAuthenticationJSONBody struct {
	CredentialType CredentialType `json:"credential_type"`
	DomainId       DomainId       `json:"domain_id"`
	Identifier     Identifier     `json:"identifier"`

	// accno:account number, idcard:id card, mobile:mobile phone, email:email address
	IdentifierType IdentifierType `json:"identifier_type"`
}

// GetIdentifierIdJSONBody defines parameters for GetIdentifierId.
type GetIdentifierIdJSONBody struct {
	DomainId   DomainId   `json:"domain_id"`
	Identifier Identifier `json:"identifier"`

	// accno:account number, idcard:id card, mobile:mobile phone, email:email address
	IdentifierType IdentifierType `json:"identifier_type"`
}

// RequestIdentifierVerifyTokenJSONBody defines parameters for RequestIdentifierVerifyToken.
type RequestIdentifierVerifyTokenJSONBody struct {
	DomainId   DomainId   `json:"domain_id"`
	Identifier Identifier `json:"identifier"`

	// accno:account number, idcard:id card, mobile:mobile phone, email:email address
	IdentifierType IdentifierType `json:"identifier_type"`
}

// DeleteIdentifierJSONBody defines parameters for DeleteIdentifier.
type DeleteIdentifierJSONBody struct {
	// token generated after credential check
	Token AuthenticatedToken `json:"token"`
}

// ChangeIdentifierJSONBody defines parameters for ChangeIdentifier.
type ChangeIdentifierJSONBody struct {
	// token use in identifer's verification
	IdentifierVerifyToken *IdentifierVerifyToken `json:"identifier_verify_token,omitempty"`
	Idetifier             Identifier             `json:"idetifier"`

	// token generated after credential check
	Token AuthenticatedToken `json:"token"`
}

// CreateIdentityJSONBody defines parameters for CreateIdentity.
type CreateIdentityJSONBody Identity

// DeleteIdentityJSONBody defines parameters for DeleteIdentity.
type DeleteIdentityJSONBody struct {
	// token generated after credential check
	Token AuthenticatedToken `json:"token"`
}

// DeleteCredentialOfIdentityJSONBody defines parameters for DeleteCredentialOfIdentity.
type DeleteCredentialOfIdentityJSONBody struct {
	// token generated after credential check
	Token AuthenticatedToken `json:"token"`
}

// UpdateCredentialOfIdentityJSONBody defines parameters for UpdateCredentialOfIdentity.
type UpdateCredentialOfIdentityJSONBody struct {
	Config CredentialConfig `json:"config"`

	// token generated after credential check
	Token AuthenticatedToken `json:"token"`
}

// UnbindIdentifierToCredentialOfIdentityJSONBody defines parameters for UnbindIdentifierToCredentialOfIdentity.
type UnbindIdentifierToCredentialOfIdentityJSONBody struct {
	DomainId   DomainId   `json:"domain_id"`
	Identifier Identifier `json:"identifier"`

	// accno:account number, idcard:id card, mobile:mobile phone, email:email address
	IdentifierType IdentifierType `json:"identifier_type"`

	// token generated after credential check
	Token AuthenticatedToken `json:"token"`
}

// BindIdentifierToCredentialOfIdentityJSONBody defines parameters for BindIdentifierToCredentialOfIdentity.
type BindIdentifierToCredentialOfIdentityJSONBody struct {
	DomainId   DomainId   `json:"domain_id"`
	Identifier Identifier `json:"identifier"`

	// accno:account number, idcard:id card, mobile:mobile phone, email:email address
	IdentifierType IdentifierType `json:"identifier_type"`

	// token generated after credential check
	Token AuthenticatedToken `json:"token"`
}

// CreateIdentityIdentiferJSONBody defines parameters for CreateIdentityIdentifer.
type CreateIdentityIdentiferJSONBody struct {
	IdentifierCredentials IdentifierCredentials `json:"identifier_credentials"`

	// token generated after credential check
	Token AuthenticatedToken `json:"token"`
}

// UpdateIdentityStateJSONBody defines parameters for UpdateIdentityState.
type UpdateIdentityStateJSONBody struct {
	State State `json:"state"`

	// token generated after credential check
	Token AuthenticatedToken `json:"token"`
}

// CheckCredentialForAuthenticationJSONRequestBody defines body for CheckCredentialForAuthentication for application/json ContentType.
type CheckCredentialForAuthenticationJSONRequestBody CheckCredentialForAuthenticationJSONBody

// GenerateCredentialForAuthenticationJSONRequestBody defines body for GenerateCredentialForAuthentication for application/json ContentType.
type GenerateCredentialForAuthenticationJSONRequestBody GenerateCredentialForAuthenticationJSONBody

// GetIdentifierIdJSONRequestBody defines body for GetIdentifierId for application/json ContentType.
type GetIdentifierIdJSONRequestBody GetIdentifierIdJSONBody

// RequestIdentifierVerifyTokenJSONRequestBody defines body for RequestIdentifierVerifyToken for application/json ContentType.
type RequestIdentifierVerifyTokenJSONRequestBody RequestIdentifierVerifyTokenJSONBody

// DeleteIdentifierJSONRequestBody defines body for DeleteIdentifier for application/json ContentType.
type DeleteIdentifierJSONRequestBody DeleteIdentifierJSONBody

// ChangeIdentifierJSONRequestBody defines body for ChangeIdentifier for application/json ContentType.
type ChangeIdentifierJSONRequestBody ChangeIdentifierJSONBody

// CreateIdentityJSONRequestBody defines body for CreateIdentity for application/json ContentType.
type CreateIdentityJSONRequestBody CreateIdentityJSONBody

// DeleteIdentityJSONRequestBody defines body for DeleteIdentity for application/json ContentType.
type DeleteIdentityJSONRequestBody DeleteIdentityJSONBody

// DeleteCredentialOfIdentityJSONRequestBody defines body for DeleteCredentialOfIdentity for application/json ContentType.
type DeleteCredentialOfIdentityJSONRequestBody DeleteCredentialOfIdentityJSONBody

// UpdateCredentialOfIdentityJSONRequestBody defines body for UpdateCredentialOfIdentity for application/json ContentType.
type UpdateCredentialOfIdentityJSONRequestBody UpdateCredentialOfIdentityJSONBody

// UnbindIdentifierToCredentialOfIdentityJSONRequestBody defines body for UnbindIdentifierToCredentialOfIdentity for application/json ContentType.
type UnbindIdentifierToCredentialOfIdentityJSONRequestBody UnbindIdentifierToCredentialOfIdentityJSONBody

// BindIdentifierToCredentialOfIdentityJSONRequestBody defines body for BindIdentifierToCredentialOfIdentity for application/json ContentType.
type BindIdentifierToCredentialOfIdentityJSONRequestBody BindIdentifierToCredentialOfIdentityJSONBody

// CreateIdentityIdentiferJSONRequestBody defines body for CreateIdentityIdentifer for application/json ContentType.
type CreateIdentityIdentiferJSONRequestBody CreateIdentityIdentiferJSONBody

// UpdateIdentityStateJSONRequestBody defines body for UpdateIdentityState for application/json ContentType.
type UpdateIdentityStateJSONRequestBody UpdateIdentityStateJSONBody
